import { createHash } from "node:crypto";

import {
  ArgosLocalModelCatalog,
  type EvaluatedLocalModel,
  type ArgosIndexEntry,
  type LocalModelCandidate,
  type LocalModelSourceSnapshot,
  type SignedCatalogRelease,
} from "@research-video/providers/local-model-argos-catalog";
import { LocalModelEvaluationFindingSchema } from "@research-video/contracts";
import {
  asCloudDatabase,
  type CloudDatabase,
  type CloudDatabaseInput,
  type CloudQueryRow,
} from "@research-video/db-cloud";
import type { TranscriptObjectStore } from "@research-video/storage";

export type LocalModelOperationKind =
  | "refresh_source"
  | "evaluate_candidate"
  | "mirror_artifact"
  | "publish_catalog_release";
export type LocalModelOperationState =
  "queued" | "running" | "succeeded" | "failed" | "canceled";

export type DurableLocalModelOperation = {
  id: string;
  kind: LocalModelOperationKind;
  idempotencyKey: string;
  sourceId?: string;
  candidateId?: string;
  catalogReleaseId?: string;
  state: LocalModelOperationState;
  version: number;
  progressPercent: number;
  createdAt: string;
  startedAt?: string;
  heartbeatAt?: string;
  leaseOwner?: string;
  leaseExpiresAt?: string;
  finishedAt?: string;
  sanitizedFailureCode?: string;
};

export type EnqueueLocalModelOperation = {
  /** A UUID generated by the command boundary; it is never derived from input. */
  id: string;
  kind: LocalModelOperationKind;
  idempotencyKey: string;
  createdBy: string;
  createdAt: string;
  sourceId?: string;
  candidateId?: string;
  catalogReleaseId?: string;
};

export type ArgosSource = {
  id: string;
  sourceUrl: string;
  state: "enabled" | "disabled";
  refreshIntervalHours: number;
  lastFetchedAt?: string;
};

export type ImmutableArtifact = {
  id: string;
  sha256: string;
  byteSize: number;
};

export interface ImmutableArtifactStore {
  putImmutable(
    kind: "raw_feed" | "raw_candidate" | "artifact" | "evaluation",
    bytes: Uint8Array,
  ): Promise<ImmutableArtifact>;
  read(id: string): Promise<Uint8Array>;
}

/** Small object-store boundary used by the server composition layer. */
export interface ImmutableByteObjectStore {
  putIfAbsent(key: string, bytes: Uint8Array): Promise<void>;
  get(key: string): Promise<Uint8Array | undefined>;
}

export class TranscriptImmutableByteObjectStore implements ImmutableByteObjectStore {
  constructor(private readonly objects: TranscriptObjectStore) {}

  async putIfAbsent(key: string, bytes: Uint8Array): Promise<void> {
    const expected = sha256Bytes(bytes);
    const existing = await this.objects.get(key);
    if (existing) {
      if (existing.sha256 !== expected)
        throw new Error("immutable_key_collision");
      return;
    }
    const stored = await this.objects.put({
      key,
      bytes,
      contentType: "application/octet-stream",
      sha256: expected,
    });
    if (stored.sha256 !== expected)
      throw new Error("artifact_integrity_mismatch");
  }

  async get(key: string): Promise<Uint8Array | undefined> {
    const stored = await this.objects.get(key);
    if (!stored) return undefined;
    if (sha256Bytes(stored.bytes) !== stored.sha256)
      throw new Error("artifact_integrity_mismatch");
    return stored.bytes;
  }
}

export class ContentAddressedImmutableArtifactStore implements ImmutableArtifactStore {
  constructor(private readonly objects: ImmutableByteObjectStore) {}
  async putImmutable(
    kind: "raw_feed" | "raw_candidate" | "artifact" | "evaluation",
    bytes: Uint8Array,
  ): Promise<ImmutableArtifact> {
    const sha256 = sha256Bytes(bytes);
    const id = `language-model/${kind}/${sha256}`;
    await this.objects.putIfAbsent(id, bytes);
    return { id, sha256, byteSize: bytes.byteLength };
  }
  async read(id: string): Promise<Uint8Array> {
    const bytes = await this.objects.get(id);
    if (!bytes) throw new Error("immutable_artifact_missing");
    return bytes;
  }
}

export interface ArgosSourceAdapter {
  fetchFeed(sourceUrl: string): Promise<string>;
  fetchArtifact(artifactUrl: string): Promise<Uint8Array>;
}

export class HttpArgosSourceAdapter implements ArgosSourceAdapter {
  constructor(
    private readonly fetcher: typeof fetch = fetch,
    private readonly maxFeedBytes = 20_000_000,
    private readonly maxArtifactBytes = 1_000_000_000,
  ) {}

  async fetchFeed(sourceUrl: string): Promise<string> {
    const bytes = await this.#fetchBounded(sourceUrl, this.maxFeedBytes);
    return new TextDecoder("utf-8", { fatal: true }).decode(bytes);
  }

  async fetchArtifact(artifactUrl: string): Promise<Uint8Array> {
    return this.#fetchBounded(artifactUrl, this.maxArtifactBytes);
  }

  async #fetchBounded(url: string, maxBytes: number): Promise<Uint8Array> {
    const parsed = new URL(url);
    if (parsed.protocol !== "https:") throw new Error("unsafe_source_url");
    const response = await this.fetcher(parsed, {
      redirect: "follow",
      signal: AbortSignal.timeout(60_000),
      headers: { accept: "application/octet-stream, application/json" },
    });
    if (!response.ok) throw new Error("source_fetch_failed");
    if (new URL(response.url || parsed).protocol !== "https:")
      throw new Error("unsafe_source_url");
    const declared = Number(response.headers.get("content-length"));
    if (Number.isFinite(declared) && declared > maxBytes)
      throw new Error("source_byte_limit_exceeded");
    const bytes = new Uint8Array(await response.arrayBuffer());
    if (bytes.byteLength === 0 || bytes.byteLength > maxBytes)
      throw new Error("source_byte_limit_exceeded");
    return bytes;
  }
}

/** Persistence boundary backed by 0046 in production; tests use a deterministic fake. */
export interface LocalModelOperationStore {
  getOperation(id: string): Promise<DurableLocalModelOperation | undefined>;
  claim(
    id: string,
    workerId: string,
    now: string,
    leaseExpiresAt: string,
  ): Promise<DurableLocalModelOperation | undefined>;
  heartbeat(
    id: string,
    workerId: string,
    now: string,
    leaseExpiresAt: string,
  ): Promise<DurableLocalModelOperation | undefined>;
  complete(
    id: string,
    workerId: string,
    now: string,
    progressPercent: number,
  ): Promise<DurableLocalModelOperation>;
  fail(
    id: string,
    workerId: string,
    now: string,
    code: string,
  ): Promise<DurableLocalModelOperation>;
  listDueSources(now: string, limit: number): Promise<ArgosSource[]>;
  getSource(id: string): Promise<ArgosSource | undefined>;
  putSnapshot(
    snapshot: LocalModelSourceSnapshot,
    rawFeed: ImmutableArtifact,
  ): Promise<void>;
  putCandidate(
    candidate: LocalModelCandidate,
    rawEntry: ImmutableArtifact,
  ): Promise<void>;
  getCandidate(id: string): Promise<LocalModelCandidate | undefined>;
  putEvaluation(
    evaluation: EvaluatedLocalModel,
    evidence: ImmutableArtifact,
    artifact?: ImmutableArtifact,
  ): Promise<void>;
  finishCandidateEvaluation(
    candidateId: string,
    state: "evaluated" | "rejected",
  ): Promise<void>;
  getEvaluation(
    candidateId: string,
  ): Promise<
    | { evaluation: EvaluatedLocalModel; artifact?: ImmutableArtifact }
    | undefined
  >;
  putMirror(evaluationId: string, artifact: ImmutableArtifact): Promise<void>;
  putRelease(release: SignedCatalogRelease): Promise<void>;
}

export class DurableLocalModelOperationRunner {
  constructor(
    private readonly store: LocalModelOperationStore,
    private readonly artifacts: ImmutableArtifactStore,
    private readonly source: ArgosSourceAdapter,
    private readonly catalog: ArgosLocalModelCatalog,
    private readonly now: () => Date = () => new Date(),
    private readonly leaseMs = 60_000,
  ) {}

  async discoverDueSources(limit = 100): Promise<ArgosSource[]> {
    return this.store.listDueSources(
      this.now().toISOString(),
      Math.min(Math.max(limit, 1), 100),
    );
  }

  async heartbeat(
    operationId: string,
    workerId: string,
  ): Promise<DurableLocalModelOperation | undefined> {
    const now = this.now();
    return this.store.heartbeat(
      operationId,
      workerId,
      now.toISOString(),
      new Date(now.getTime() + this.leaseMs).toISOString(),
    );
  }

  async run(
    operationId: string,
    workerId: string,
  ): Promise<DurableLocalModelOperation | undefined> {
    const existing = await this.store.getOperation(operationId);
    if (
      !existing ||
      existing.state === "succeeded" ||
      existing.state === "failed" ||
      existing.state === "canceled"
    )
      return existing;
    const now = this.now();
    const claimed = await this.store.claim(
      operationId,
      workerId,
      now.toISOString(),
      new Date(now.getTime() + this.leaseMs).toISOString(),
    );
    if (!claimed) return this.store.getOperation(operationId);
    try {
      await this.#runClaimed(claimed, workerId);
      return this.store.complete(
        operationId,
        workerId,
        this.now().toISOString(),
        100,
      );
    } catch (error) {
      return this.store.fail(
        operationId,
        workerId,
        this.now().toISOString(),
        sanitizeFailure(error),
      );
    }
  }

  async #runClaimed(
    operation: DurableLocalModelOperation,
    workerId: string,
  ): Promise<void> {
    await this.heartbeat(operation.id, workerId);
    if (operation.kind === "refresh_source")
      return this.#refresh(operation, workerId);
    if (operation.kind === "evaluate_candidate")
      return this.#evaluate(operation, workerId);
    if (operation.kind === "mirror_artifact")
      return this.#mirror(operation, workerId);
    return this.#publish(operation, workerId);
  }

  async #refresh(
    operation: DurableLocalModelOperation,
    workerId: string,
  ): Promise<void> {
    if (
      !operation.sourceId ||
      operation.candidateId ||
      operation.catalogReleaseId
    )
      throw new Error("invalid_operation_reference");
    const source = await this.store.getSource(operation.sourceId);
    if (!source || source.state !== "enabled")
      throw new Error("source_unavailable");
    const rawFeed = await this.source.fetchFeed(source.sourceUrl);
    const feedBytes = new TextEncoder().encode(rawFeed);
    const rawArtifact = await this.artifacts.putImmutable(
      "raw_feed",
      feedBytes,
    );
    const { snapshot, candidates } = this.catalog.discover(
      rawFeed,
      this.now().toISOString(),
    );
    if (snapshot.feedSha256 !== rawArtifact.sha256)
      throw new Error("feed_integrity_mismatch");
    await this.store.putSnapshot(snapshot, rawArtifact);
    for (const candidate of candidates) {
      const rawEntry = await this.artifacts.putImmutable(
        "raw_candidate",
        new TextEncoder().encode(stableJson(candidate.rawEntry)),
      );
      await this.store.putCandidate(candidate, rawEntry);
    }
    await this.heartbeat(operation.id, workerId);
  }

  async #evaluate(
    operation: DurableLocalModelOperation,
    workerId: string,
  ): Promise<void> {
    if (
      !operation.candidateId ||
      operation.sourceId ||
      operation.catalogReleaseId
    )
      throw new Error("invalid_operation_reference");
    const candidate = await this.store.getCandidate(operation.candidateId);
    if (!candidate) throw new Error("candidate_not_found");
    let fetched: Uint8Array | undefined;
    const evaluation = await this.catalog.evaluate(
      candidate,
      async (url) => {
        fetched = await this.source.fetchArtifact(url);
        return fetched;
      },
      this.now().toISOString(),
    );
    const artifact = fetched
      ? await this.artifacts.putImmutable("artifact", fetched)
      : undefined;
    const evidence = await this.artifacts.putImmutable(
      "evaluation",
      new TextEncoder().encode(stableJson(evaluation)),
    );
    await this.store.putEvaluation(evaluation, evidence, artifact);
    this.catalog.register(evaluation);
    const hardSafe =
      Boolean(artifact) &&
      !evaluation.findings.some((finding) => finding.severity === "hard");
    if (hardSafe && artifact) {
      await this.store.putMirror(evaluation.id, artifact);
    }
    await this.store.finishCandidateEvaluation(
      evaluation.candidate.id,
      hardSafe ? "evaluated" : "rejected",
    );
    await this.heartbeat(operation.id, workerId);
  }

  async #mirror(
    operation: DurableLocalModelOperation,
    workerId: string,
  ): Promise<void> {
    if (
      !operation.candidateId ||
      operation.sourceId ||
      operation.catalogReleaseId
    )
      throw new Error("invalid_operation_reference");
    const evaluation = await this.store.getEvaluation(operation.candidateId);
    if (
      !evaluation?.artifact ||
      evaluation.artifact.sha256 !== evaluation.evaluation.artifactSha256
    )
      throw new Error("exact_artifact_unavailable");
    const bytes = await this.artifacts.read(evaluation.artifact.id);
    if (sha256(bytes) !== evaluation.artifact.sha256)
      throw new Error("artifact_integrity_mismatch");
    const mirrored = await this.artifacts.putImmutable("artifact", bytes);
    await this.store.putMirror(evaluation.evaluation.id, mirrored);
    await this.heartbeat(operation.id, workerId);
  }

  async #publish(
    operation: DurableLocalModelOperation,
    workerId: string,
  ): Promise<void> {
    if (
      !operation.catalogReleaseId ||
      operation.sourceId ||
      operation.candidateId
    )
      throw new Error("invalid_operation_reference");
    const release = await this.catalog.publish();
    if (release.id !== operation.catalogReleaseId)
      throw new Error("release_identity_mismatch");
    await this.store.putRelease(release);
    await this.heartbeat(operation.id, workerId);
  }
}

/**
 * Direct 0046 persistence adapter. Engine hash identities remain evidence in
 * JSON/artifacts; deterministic UUIDs are used only for relational keys.
 */
export class CloudDatabaseLocalModelOperationStore implements LocalModelOperationStore {
  readonly #database: CloudDatabase;
  constructor(
    database: CloudDatabaseInput,
    private readonly actorId?: string,
  ) {
    this.#database = asCloudDatabase(database);
  }

  /**
   * Atomically creates one durable operation per actor/idempotency key. A
   * repeated delivery returns the original operation only when its immutable
   * kind and reference are identical; reusing the key for another command is
   * rejected instead of silently running the wrong work.
   */
  async enqueue(
    input: EnqueueLocalModelOperation,
  ): Promise<DurableLocalModelOperation> {
    assertOperationReference(input);
    return this.#database.transaction(async () => {
      const existing = await this.#database.query<CloudQueryRow>(
        `SELECT * FROM local_model_operations
         WHERE created_by = $1 AND idempotency_key = $2`,
        [input.createdBy, input.idempotencyKey],
      );
      if (existing.rows[0]) {
        const operation = mapOperation(existing.rows[0])!;
        if (!sameOperationIntent(operation, input))
          throw new Error("idempotency_key_reused_with_different_operation");
        return operation;
      }
      const result = await this.#database.query<CloudQueryRow>(
        `INSERT INTO local_model_operations
           (id, kind, source_id, candidate_id, catalog_release_id, state,
            version, idempotency_key, progress_percent, created_by, created_at)
         VALUES ($1, $2, $3, $4, $5, 'queued', 1, $6, 0, $7, $8)
         RETURNING *`,
        [
          input.id,
          input.kind,
          input.sourceId ?? null,
          input.candidateId ?? null,
          input.catalogReleaseId ?? null,
          input.idempotencyKey,
          input.createdBy,
          input.createdAt,
        ],
      );
      return mapOperation(result.rows[0])!;
    });
  }
  async getOperation(id: string) {
    return mapOperation(
      (
        await this.#database.query<CloudQueryRow>(
          "SELECT * FROM local_model_operations WHERE id = $1",
          [id],
        )
      ).rows[0],
    );
  }
  async claim(
    id: string,
    workerId: string,
    now: string,
    leaseExpiresAt: string,
  ) {
    const result = await this.#database.query<CloudQueryRow>(
      `UPDATE local_model_operations SET state = 'running', version = version + 1, started_at = COALESCE(started_at, $3), heartbeat_at = $3, lease_owner = $2, lease_expires_at = $4 WHERE id = $1 AND state IN ('queued', 'running') AND (state = 'queued' OR lease_expires_at <= $3 OR lease_owner = $2) RETURNING *`,
      [id, workerId, now, leaseExpiresAt],
    );
    return mapOperation(result.rows[0]);
  }
  async heartbeat(
    id: string,
    workerId: string,
    now: string,
    leaseExpiresAt: string,
  ) {
    const result = await this.#database.query<CloudQueryRow>(
      `UPDATE local_model_operations SET version = version + 1, heartbeat_at = $3, lease_expires_at = $4 WHERE id = $1 AND state = 'running' AND lease_owner = $2 AND lease_expires_at > $3 RETURNING *`,
      [id, workerId, now, leaseExpiresAt],
    );
    return mapOperation(result.rows[0]);
  }
  async complete(
    id: string,
    workerId: string,
    now: string,
    progressPercent: number,
  ) {
    return this.#terminal(id, workerId, now, "succeeded", progressPercent);
  }
  async fail(id: string, workerId: string, now: string, code: string) {
    return this.#terminal(id, workerId, now, "failed", undefined, code);
  }
  async #terminal(
    id: string,
    workerId: string,
    now: string,
    state: "succeeded" | "failed",
    progress?: number,
    code?: string,
  ) {
    const result = await this.#database.query<CloudQueryRow>(
      `UPDATE local_model_operations SET state = $3, version = version + 1, progress_percent = COALESCE($4, progress_percent), sanitized_failure_code = $5, finished_at = $6, lease_owner = NULL, lease_expires_at = NULL WHERE id = $1 AND state = 'running' AND lease_owner = $2 AND lease_expires_at > $6 RETURNING *`,
      [
        id,
        workerId,
        state,
        progress ?? null,
        code ? sanitizeFailureCode(code) : null,
        now,
      ],
    );
    const mapped = mapOperation(result.rows[0]);
    if (!mapped) throw new Error("lease_lost");
    return mapped;
  }
  /** Requeues a terminal failure with optimistic concurrency for an explicit retry. */
  async retry(
    id: string,
    expectedVersion: number,
    now: string,
  ): Promise<DurableLocalModelOperation | undefined> {
    const result = await this.#database.query<CloudQueryRow>(
      `UPDATE local_model_operations
       SET state = 'queued', version = version + 1, progress_percent = 0,
           sanitized_failure_code = NULL, started_at = NULL, heartbeat_at = NULL,
           lease_owner = NULL, lease_expires_at = NULL, finished_at = NULL,
           attempt = attempt + 1, last_retried_at = $3
       WHERE id = $1 AND state = 'failed' AND version = $2
       RETURNING *`,
      [id, expectedVersion, now],
    );
    return mapOperation(result.rows[0]);
  }
  /**
   * Recovery is deliberately separate from claiming: it only releases stale
   * work. A later claim atomically assigns a new worker, so an old worker can
   * neither heartbeat nor terminally complete after its lease has expired.
   */
  async recoverExpiredLeases(
    now: string,
    limit = 100,
  ): Promise<DurableLocalModelOperation[]> {
    const result = await this.#database.query<CloudQueryRow>(
      `WITH expired AS (
         SELECT id FROM local_model_operations
         WHERE state = 'running' AND lease_expires_at <= $1
         ORDER BY lease_expires_at, id
         LIMIT $2
         FOR UPDATE SKIP LOCKED
       )
       UPDATE local_model_operations operation
       SET state = 'queued', version = operation.version + 1,
           lease_owner = NULL, lease_expires_at = NULL
       FROM expired
       WHERE operation.id = expired.id
       RETURNING operation.*`,
      [now, Math.min(Math.max(limit, 1), 1_000)],
    );
    return result.rows
      .map(mapOperation)
      .filter(
        (operation): operation is DurableLocalModelOperation =>
          operation !== undefined,
      );
  }
  async listDueSources(now: string, limit: number) {
    const result = await this.#database.query<CloudQueryRow>(
      `SELECT s.*, max(f.fetched_at) AS last_fetched_at FROM local_model_sources s LEFT JOIN local_model_feed_snapshots f ON f.source_id = s.id WHERE s.state = 'enabled' GROUP BY s.id HAVING max(f.fetched_at) IS NULL OR max(f.fetched_at) + (s.refresh_interval_hours * interval '1 hour') <= $1 ORDER BY s.id LIMIT $2`,
      [now, limit],
    );
    return result.rows
      .map(mapSource)
      .filter((source): source is ArgosSource => source !== undefined);
  }
  async getSource(id: string) {
    return mapSource(
      (
        await this.#database.query<CloudQueryRow>(
          "SELECT * FROM local_model_sources WHERE id = $1",
          [id],
        )
      ).rows[0],
    );
  }
  async putSnapshot(
    snapshot: LocalModelSourceSnapshot,
    rawFeed: ImmutableArtifact,
  ) {
    await this.#database.query(
      `INSERT INTO local_model_feed_snapshots (id, source_id, source_url, feed_sha256, raw_feed_artifact_id, raw_feed_byte_size, fetched_at, additions, changes, removals) VALUES ($1, $2, $3, $4, $5, $6, $7, 0, 0, 0) ON CONFLICT (source_id, feed_sha256) DO NOTHING`,
      [
        uuid(snapshot.id),
        snapshot.sourceId,
        snapshot.sourceUrl,
        snapshot.feedSha256,
        rawFeed.id,
        rawFeed.byteSize,
        snapshot.fetchedAt,
      ],
    );
  }
  async putCandidate(
    candidate: LocalModelCandidate,
    rawEntry: ImmutableArtifact,
  ) {
    await this.#database.query(
      `INSERT INTO local_model_candidates (id, source_id, feed_snapshot_id, source_language, target_language, package_version, runtime_family, runtime_version, artifact_url, raw_entry, raw_entry_sha256, raw_entry_artifact_id, state, version, discovered_at) VALUES ($1, $2, $3, $4, $5, $6, 'argos-translate', 'unknown', $7, $8, $9, $10, 'discovered', 1, now()) ON CONFLICT (id) DO NOTHING`,
      [
        uuid(candidate.id),
        candidate.sourceId,
        uuid(candidate.snapshotId),
        candidate.sourceLanguage,
        candidate.targetLanguage,
        candidate.packageVersion,
        candidate.artifactUrl,
        JSON.stringify({
          engineId: candidate.id,
          snapshotId: candidate.snapshotId,
          rawEntry: candidate.rawEntry,
        }),
        rawEntry.sha256,
        rawEntry.id,
      ],
    );
  }
  async getCandidate(id: string) {
    const row = (
      await this.#database.query<CloudQueryRow>(
        "SELECT * FROM local_model_candidates WHERE id = $1",
        [id],
      )
    ).rows[0];
    if (!row) return undefined;
    const raw = parseJson(row.raw_entry) as {
      engineId: string;
      snapshotId: string;
      rawEntry: Record<string, unknown>;
    };
    return {
      id: raw.engineId,
      snapshotId: raw.snapshotId,
      sourceId: "argos-package-index" as const,
      artifactUrl: String(row.artifact_url),
      sourceLanguage: String(row.source_language),
      targetLanguage: String(row.target_language),
      packageVersion: String(row.package_version),
      rawEntry: raw.rawEntry as ArgosIndexEntry,
    };
  }
  async putEvaluation(
    evaluation: EvaluatedLocalModel,
    evidence: ImmutableArtifact,
    artifact?: ImmutableArtifact,
  ) {
    const evaluationActor =
      this.actorId ??
      String(
        (
          await this.#database.query<CloudQueryRow>(
            `SELECT created_by FROM local_model_operations
             WHERE kind = 'evaluate_candidate' AND candidate_id = $1
             ORDER BY created_at DESC LIMIT 1`,
            [uuid(evaluation.candidate.id)],
          )
        ).rows[0]?.created_by ?? "",
      );
    if (!evaluationActor) throw new Error("evaluation_actor_unavailable");
    const findings = mapLocalModelEvaluationFindings(evaluation.findings);
    await this.#database.query(
      `INSERT INTO local_model_evaluations (id, candidate_id, revision, evaluation_schema_version, evaluated_by, raw_evidence_artifact_ids, byte_size, artifact_sha256, archive_format, archive_manifest, license_evidence, attribution_evidence, training_provenance_evidence, quality_results, compatible_runtime_versions, compatible_platforms, findings, evaluated_at) VALUES ($1, $2, 1, 1, $3, $4, $5, $6, 'argosmodel', $7, $8, $8, $8, $9, $10, $11, $12, $13) ON CONFLICT (id) DO NOTHING`,
      [
        uuid(evaluation.id),
        uuid(evaluation.candidate.id),
        evaluationActor,
        JSON.stringify([evidence.id]),
        evaluation.byteSize,
        evaluation.artifactSha256,
        JSON.stringify(evaluation.archive ?? {}),
        JSON.stringify(["artifact-evidence"]),
        JSON.stringify({
          engineId: evaluation.id,
          recommendation: evaluation.recommendation,
          runtimeFamily: evaluation.runtimeFamily,
          runtimeVersion: evaluation.runtimeVersion,
          artifactId: artifact?.id,
        }),
        JSON.stringify([evaluation.runtimeVersion ?? "unknown"]),
        JSON.stringify(["desktop"]),
        JSON.stringify(findings),
        evaluation.evaluatedAt,
      ],
    );
  }
  async finishCandidateEvaluation(
    candidateId: string,
    state: "evaluated" | "rejected",
  ) {
    const updated = await this.#database.query(
      `UPDATE local_model_candidates
       SET state = $2, version = version + 1
       WHERE id = $1 AND state = 'evaluating' RETURNING id`,
      [uuid(candidateId), state],
    );
    if (!updated.rows[0]) throw new Error("candidate_state_conflict");
  }
  async getEvaluation(candidateId: string) {
    const row = (
      await this.#database.query<CloudQueryRow>(
        `SELECT e.*, c.raw_entry, c.artifact_url, c.source_language,
                c.target_language, c.package_version
         FROM local_model_evaluations e
         JOIN local_model_candidates c ON c.id = e.candidate_id
         WHERE e.candidate_id = $1
         ORDER BY e.revision DESC LIMIT 1`,
        [candidateId],
      )
    ).rows[0];
    if (!row) return undefined;
    const raw = parseJson(row.raw_entry) as {
      engineId: string;
      snapshotId: string;
      rawEntry: Record<string, unknown>;
    };
    const candidate: LocalModelCandidate = {
      id: raw.engineId,
      snapshotId: raw.snapshotId,
      sourceId: "argos-package-index" as const,
      artifactUrl: String(row.artifact_url),
      sourceLanguage: String(row.source_language),
      targetLanguage: String(row.target_language),
      packageVersion: String(row.package_version),
      rawEntry: raw.rawEntry as ArgosIndexEntry,
    };
    const quality = parseJson(row.quality_results) as Record<string, unknown>;
    const evaluation = {
      id: String(quality.engineId ?? row.id),
      candidate,
      artifactSha256: String(row.artifact_sha256),
      byteSize: Number(row.byte_size),
      archive: undefined,
      findings: parseJson(row.findings),
      evaluatedAt: new Date(row.evaluated_at as string).toISOString(),
      runtimeFamily: String(quality.runtimeFamily ?? "argos"),
      ...(typeof quality.runtimeVersion === "string"
        ? { runtimeVersion: quality.runtimeVersion }
        : {}),
      recommendation: quality.recommendation,
    } as EvaluatedLocalModel;
    const artifactId = quality.artifactId as string | undefined;
    return {
      evaluation,
      ...(artifactId
        ? {
            artifact: {
              id: artifactId,
              sha256: evaluation.artifactSha256,
              byteSize: evaluation.byteSize,
            },
          }
        : {}),
    };
  }
  async putMirror(evaluationId: string, artifact: ImmutableArtifact) {
    await this.#database.query(
      `INSERT INTO local_model_versions (id, candidate_id, evaluation_id, source_language, target_language, runtime_family, artifact_sha256, artifact_byte_size, mirrored_artifact_id)
       SELECT $1, e.candidate_id, e.id, c.source_language, c.target_language,
              c.runtime_family, e.artifact_sha256, e.byte_size, $2
       FROM local_model_evaluations e
       JOIN local_model_candidates c ON c.id = e.candidate_id
       WHERE e.id = $3
       ON CONFLICT (evaluation_id) DO NOTHING`,
      [uuid(`mirror:${evaluationId}`), artifact.id, uuid(evaluationId)],
    );
  }
  async putRelease(release: SignedCatalogRelease) {
    await this.#database.transaction(async () => {
      const releaseId = uuid(release.id);
      await this.#database.query(
        `INSERT INTO signed_local_model_catalog_releases (id, sequence, catalog_sha256, signing_key_id, signature_base64, published_at)
         VALUES ($1, $2, $3, $4, $5, now()) ON CONFLICT (id) DO NOTHING`,
        [
          releaseId,
          Math.max(release.payload.catalogRevision, 1),
          sha256(new TextEncoder().encode(release.canonicalPayload)),
          release.keyId,
          release.signature,
        ],
      );
      for (const model of release.payload.models) {
        await this.#database.query(
          `INSERT INTO signed_local_model_catalog_release_versions
             (release_id, local_model_version_id)
           SELECT $1, id FROM local_model_versions WHERE evaluation_id = $2
           ON CONFLICT DO NOTHING`,
          [releaseId, uuid(model.id)],
        );
      }
    });
  }
}

export function mapLocalModelEvaluationFindings(
  findings: EvaluatedLocalModel["findings"],
) {
  return findings.map((finding) =>
    LocalModelEvaluationFindingSchema.parse({
      code: finding.code,
      class: finding.severity === "hard" ? "hard_safety" : "recommendation",
      state: finding.severity === "hard" ? "fail" : "not_recommended",
      message: finding.message,
    }),
  );
}

function uuid(value: string): string {
  const hash = sha256(new TextEncoder().encode(value));
  return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-4${hash.slice(13, 16)}-8${hash.slice(17, 20)}-${hash.slice(20, 32)}`;
}
function parseJson(value: unknown): any {
  return typeof value === "string" ? JSON.parse(value) : value;
}
function mapSource(row: CloudQueryRow | undefined): ArgosSource | undefined {
  return row
    ? {
        id: String(row.id),
        sourceUrl: String(row.source_url),
        state: row.state === "enabled" ? "enabled" : "disabled",
        refreshIntervalHours: Number(row.refresh_interval_hours),
        ...(row.last_fetched_at
          ? {
              lastFetchedAt: new Date(
                row.last_fetched_at as string,
              ).toISOString(),
            }
          : {}),
      }
    : undefined;
}
function mapOperation(
  row: CloudQueryRow | undefined,
): DurableLocalModelOperation | undefined {
  return row
    ? {
        id: String(row.id),
        kind: row.kind as LocalModelOperationKind,
        idempotencyKey: String(row.idempotency_key),
        ...(row.source_id ? { sourceId: String(row.source_id) } : {}),
        ...(row.candidate_id ? { candidateId: String(row.candidate_id) } : {}),
        ...(row.catalog_release_id
          ? { catalogReleaseId: String(row.catalog_release_id) }
          : {}),
        state: row.state as LocalModelOperationState,
        version: Number(row.version),
        progressPercent: Number(row.progress_percent),
        createdAt: new Date(row.created_at as string).toISOString(),
        ...(row.started_at
          ? { startedAt: new Date(row.started_at as string).toISOString() }
          : {}),
        ...(row.heartbeat_at
          ? { heartbeatAt: new Date(row.heartbeat_at as string).toISOString() }
          : {}),
        ...(row.lease_owner ? { leaseOwner: String(row.lease_owner) } : {}),
        ...(row.lease_expires_at
          ? {
              leaseExpiresAt: new Date(
                row.lease_expires_at as string,
              ).toISOString(),
            }
          : {}),
        ...(row.finished_at
          ? { finishedAt: new Date(row.finished_at as string).toISOString() }
          : {}),
        ...(row.sanitized_failure_code
          ? { sanitizedFailureCode: String(row.sanitized_failure_code) }
          : {}),
      }
    : undefined;
}

function sanitizeFailure(error: unknown): string {
  const message = error instanceof Error ? error.message : "";
  if (message.includes("invalid_operation_reference"))
    return "invalid_operation_reference";
  if (message.includes("integrity")) return "integrity_check_failed";
  if (message.includes("not_found")) return "source_or_candidate_not_found";
  if (message.includes("unavailable")) return "source_unavailable";
  return "local_model_operation_failed";
}

function sanitizeFailureCode(code: string): string {
  const normalized = code
    .trim()
    .replace(/[^a-z0-9._-]/gi, "_")
    .slice(0, 160);
  return normalized || "local_model_operation_failed";
}

function assertOperationReference(input: EnqueueLocalModelOperation): void {
  const source = input.sourceId !== undefined;
  const candidate = input.candidateId !== undefined;
  const release = input.catalogReleaseId !== undefined;
  const valid =
    (input.kind === "refresh_source" && source && !candidate && !release) ||
    (["evaluate_candidate", "mirror_artifact"].includes(input.kind) &&
      !source &&
      candidate &&
      !release) ||
    (input.kind === "publish_catalog_release" &&
      !source &&
      !candidate &&
      release);
  if (!valid) throw new Error("invalid_operation_reference");
}

function sameOperationIntent(
  operation: DurableLocalModelOperation,
  input: EnqueueLocalModelOperation,
): boolean {
  return (
    operation.kind === input.kind &&
    operation.sourceId === input.sourceId &&
    operation.candidateId === input.candidateId &&
    operation.catalogReleaseId === input.catalogReleaseId
  );
}

function sha256(bytes: Uint8Array): string {
  return sha256Bytes(bytes);
}

function sha256Bytes(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

function stableJson(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`;
  if (value && typeof value === "object") {
    return `{${Object.entries(value as Record<string, unknown>)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, item]) => `${JSON.stringify(key)}:${stableJson(item)}`)
      .join(",")}}`;
  }
  return JSON.stringify(value);
}
